### PR TITLE
Reformat

### PR DESCRIPTION
**Pull request by vgoliber**
Reformat code for Gradescope autograder

### CODE REVIEW

**Comment by joelgdwave** [comment]
This is such a nit. In the README file, 
`1. Erik: [1,3,2,4]`
I think you want "Erica".

**Comment by joelgdwave** [comment]
This is very nicely done. I especially like Exercise 4, which refers back to the thinking of Graph Partitioning, with insisting on 2 people in each shift. I haven't worked it all the way out.

**Review by joelgdwave — APPROVED** [review]
Please see comments. I'm interested in the numbering one, and also what your implementation of Exercise 4 looks like. Nice work.

**Comment by vgoliber** [comment]
@joelgdwave:
- I did in fact intent for it to be Erik.  The names are different between exercises 2 and 3.
- I could not figure out how to use case "labels" with the DQM solver.  If there is a way to do it, I didn't see it in the docs.  Maybe @arcondello can confirm?
- I will send you the autograder and solutions I have.

**Review by arcondello — APPROVED** [review]

**Pull request merged**
